### PR TITLE
FF1 3.4.0 API Matching

### PR DESCRIPTION
**Pull request by pbulsink**
Responds to #259. 

Will result in f1dataR 1.6.0

### CODE REVIEW

**Comment by pbulsink** [comment]
At this point it still needs tests written, changes in `plot_fastest`, removal of fixed data-raw content, updated NEWS, and updated vignettes

**Comment by pbulsink** [comment]
@SCasanova This currently deletes the `constructor_data` object in the package. Do we want to do that or deprecate it until the end of the year? Note that it still has Sauber instead of Kick/Stake, and no one has complained about that not being updated yet this season.

**Comment by pbulsink** [comment]
Note the build failure for old-fastf1 is what #261 fixes...

**Comment by pbulsink** [comment]
Note: Should rebase after #261 is merged to ensure all tests work ok.

**Comment by SCasanova** [comment]
#261 merged

**Pull request merged**
