### PR TITLE
Version bump and submission

### PR DESCRIPTION
**Pull request by SCasanova**

### CODE REVIEW

**Comment by pbulsink** [comment]
You should add .DS_Store to .gitignore instead of have it in the repo. You'll have to delete this one, commit the deletion, and commit the .gitignore change.

**Comment by pbulsink** [comment]
This PR puts the version. At 1.4.1 but we're currently at 1.5.0 in the repo

**Comment by pbulsink** [comment]
It might be easier to use a new dev branch, and discard this one, instead of having the PR carry the extra multiple_driver_telem code addition/subtraction and be behind in version num (plus removing the .DS_Store and fixing the out-of-date fastf1)

**Comment by SCasanova** [comment]
Yeah good idea

**Pull request closed without merging**
