### PR TITLE
Version bump to 1.5.0

### PR DESCRIPTION
**Pull request by pbulsink**
Version to 1.5.0 as it contains new functionality over 1.4.1.

### CODE REVIEW

**Comment by pbulsink** [comment]
@SCasanova Once this is merged can you submit to CRAN?

**Comment by SCasanova** [comment]
Absolutely. Thanks for your work on this

**Comment by SCasanova** [comment]
I'll wait for your merge

**Comment by pbulsink** [comment]
Done, ready to go.

**Comment by SCasanova** [comment]
Submitted

**Pull request merged**
