### PR TITLE
Eliminate all use of `getwd()` for `tempdir()`

### PR DESCRIPTION
**Pull request by SCasanova**
This eliminates all use of `getwd()` throughout the package and uses a temporary directory as the default for cache. Also an OS check is conducted when calling the python function to enable and delete the cache to modify the file path for Windows from the use of back slash to front slash.

Related to #161  and #157

### CODE REVIEW

**Comment by SCasanova** [comment]
Awaiting @pbulsink review before merging to navigate conflicts beforehand as we both worked on the cache functionalities.

**Comment by SCasanova** [comment]
Also, I think both PRs warrant a version change. Not sure if that affects our re-sumbission to CRAN (don't think so?)

**Comment by pbulsink** [comment]
I wonder if using `normalizePath(getOption("f1dataR.cache"))` is better than doing platform-dependent functions? This is likely a good idea anywhere we pass path from getOption to the code.

I'll do more review and let you know if I have any extra comments that might clash when we merge.

I might also close #163 and reopen to this branch instead, so that our changes hit master at the same time.

This certainly warrants a version change once both are merged, but I *think* I have a way of keeping it at v1.3 instead of being such a breaking  change with cache directory assignment that we need to go to v2.0

**Comment by SCasanova** [comment]
Hmm I didn't know that existed but you might be right. I will make those changes and run tests.

I like that idea so we keep master tidy.

I agree, and also like the idea of submitting on a new full version

**Comment by SCasanova** [comment]
Looks like it worked, much cleaner. Good catch

**Comment by SCasanova** [comment]
That's all from my end

**Comment by SCasanova** [comment]
Let m know if this is ready to merge into master @pbulsink

**Comment by pbulsink** [comment]
I'll double check things this evening, and also try bring our test coverage back up (including taking the `.onLoad()` out of the codecov counts as per `nflreadr`'s guidance).

**Comment by SCasanova** [comment]
We got a coverage failure related to exclusions

**Comment by pbulsink** [comment]
Oh Woops

If you add the following line either after the `.onLoad()` function or at the very last line of `zzz.R` that should fix it. If you do it I don't need to open a new PR to devtest.

```
# nocov end
```

**Comment by SCasanova** [comment]
Yeah I got it

**Comment by pbulsink** [comment]
On second thought, put it at the end of `.onLoad()` (line 101)

**Comment by pbulsink** [comment]
Looks good from my end, it you want to merge and follow with a version bump note on NEWS you can use this:

```
 * Updated documentation per requirements after CRAN review
 * Changed caching practice per requirements after CRAN review. 
If you previously had set a cache directory `options("f1dataR.cache" = [dir])` there will be no change. 
If you had previously not specified a cache directory, the package used to use the result of `getwd()`, so you can force that directory. 
New users can specify a default file cache location by setting `options("f1dataR.cache" = "filesystem")` or specify any other (existing) directory by setting the option. 
Cache will otherwise use memory as a default until the end of the R session or for 24h (whichever comes first). 
Caching can be turned off by setting the option to "off"
```

**Comment by SCasanova** [comment]
Will do just that!

**Pull request merged**
