### PR TITLE
Setup_fastf1 + vignette

### PR DESCRIPTION
**Pull request by pbulsink**
DRAFT Not to merge yet. 

@SCasanova any suggestions for function enhancements or vignette improvements are appreciated. 

Would a similar helper function for folks to easily update `fastf1` to the current version be worthwhile?

As per #119

### CODE REVIEW

**Comment by SCasanova** [comment]
Hmm perhaps a more dedicated vignette towards advanced use-cases (the type of analysis you do with the package for example, if you're comfortable sharing that).

**Comment by pbulsink** [comment]
> Hmm perhaps a more dedicated vignette towards advanced use-cases (the type of analysis you do with the package for example, if you're comfortable sharing that).

I think I can come up with a set of 'exploratory' analysis type things for some Ergast-derived data. That'd be a after-CRAN job I think. Is there anything extra for this setup_fastf1 vignette that you think should be added?

**Comment by SCasanova** [comment]
No, I think it's pretty thorough

**Comment by pbulsink** [comment]
I think this can be merged now... That was tough to hammer out for all the platforms.

**Comment by pbulsink** [comment]
You likely need to mark a new release in GitHub - this is v1.2.0

**Pull request merged**
